/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mauriceliddy;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
         
    }
}
