/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mauriceliddy.Project1.Driver;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.mauriceliddy.Project1.DAO.AthleteDao;
import com.github.mauriceliddy.Project1.DataManagement.*;
import com.github.mauriceliddy.Project1.DataManagement.UserDatabaseAccess;
import com.github.mauriceliddy.Project1.Model.*;

@WebServlet("/athletes")
public class App extends HttpServlet {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        System.out.println("Ran doGet()");
        
        DataInput dataInput = new DataInput();
        UserDatabaseAccess uAccess = new UserDatabaseAccess();
        
        List<Workout> masterList = dataInput.readInData();
        
         uAccess.sendCSVDataToDatabase(masterList);

         List<Athlete> athleteListFromDB = new ArrayList<>();
         athleteListFromDB = uAccess.retrieveAthletesFromDb();
         //Athlete athlete = new Athlete("Nick",3);

        resp.setContentType("application/json");
        resp.getWriter().print(athleteListFromDB);
        //out.flush();
      

    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

       // DataInput dataInput = new DataInput();
        UserDatabaseAccess uAccess = new UserDatabaseAccess();
        // List<Workout> masterList = dataInput.readInData();
        //  uAccess.sendCSVDataToDatabase(masterList);

        String name = req.getParameter("name");
        System.out.println("Just got the following name in: "+ name);
        Athlete athlete = new Athlete(name,0);
        uAccess.addAthlete(athlete);
        resp.sendRedirect("http://localhost:8080/app/");

        // if ((name = req.getParameter("name")) != null) {
        //     resp.getWriter().println("\n" + "(POST)Welcome: " + name + " you handsome devil, also a silly goose!");
        // } else {
        //     resp.getWriter().println("Post failed " + name);
        // }
    }
}
