/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mauriceliddy.Project1.Service;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.mauriceliddy.Project1.DAO.AthleteDao;
import com.github.mauriceliddy.Project1.DataManagement.*;
import com.github.mauriceliddy.Project1.DataManagement.UserDatabaseAccess;
import com.github.mauriceliddy.Project1.Model.*;

@WebServlet("/refresh")
public class Refresh extends HttpServlet {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        System.out.println("Ran doGet() in refresh");
        
        UserDatabaseAccess uAccess = new UserDatabaseAccess();
         List<UserAccount> userAccounts = new ArrayList<>();
         userAccounts = uAccess.getUsers();
        
         ObjectMapper mapper = new ObjectMapper();
         String jsonString = mapper.writeValueAsString(userAccounts);
        resp.setContentType("application/json");
        resp.getWriter().print(jsonString);

    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
System.out.println("dpPost for refresh");
    
        UserDatabaseAccess uAccess = new UserDatabaseAccess();
        uAccess.accessDatabase();
    resp.sendRedirect("http://localhost:8080/app/adminDashboard.html");
        // if ((name = req.getParameter("name")) != null) {
        //     resp.getWriter().println("\n" + "(POST)Welcome: " + name + " you handsome devil, also a silly goose!");
        // } else {
        //     resp.getWriter().println("Post failed " + name);
        // }
    }
}
