/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mauriceliddy.Project1.Service;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.mauriceliddy.Project1.DAO.AthleteDao;
import com.github.mauriceliddy.Project1.DataManagement.*;
import com.github.mauriceliddy.Project1.DataManagement.UserDatabaseAccess;
import com.github.mauriceliddy.Project1.Model.*;

@WebServlet("/users")
public class UserController extends HttpServlet {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        System.out.println("Ran doGet() in /athletes");
        
        DataInput dataInput = new DataInput();
        UserDatabaseAccess uAccess = new UserDatabaseAccess();
        
        List<Workout> masterList = dataInput.readInData();
        
         uAccess.sendCSVDataToDatabase(masterList);

         List<Athlete> athleteListFromDB = new ArrayList<>();
         athleteListFromDB = uAccess.retrieveAthletesFromDb();
         //Athlete athlete = new Athlete("Nick",3);

        resp.setContentType("application/json");
        resp.getWriter().print(athleteListFromDB);
        //out.flush();
      

    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        System.out.println("in doPost for /athletes");
       // DataInput dataInput = new DataInput();
        UserDatabaseAccess uAccess = new UserDatabaseAccess();
        // List<Workout> masterList = dataInput.readInData();
        //  uAccess.sendCSVDataToDatabase(masterList);

        String name = req.getParameter("name");
        String password = req.getParameter("password");
        System.out.println("Just got the following name in: "+ name);
        UserAccount uAccount = new UserAccount(0,name,password);
        uAccess.addUser(uAccount);
        resp.sendRedirect("dashboard.html");

        // if ((name = req.getParameter("name")) != null) {
        //     resp.getWriter().println("\n" + "(POST)Welcome: " + name + " you handsome devil, also a silly goose!");
        // } else {
        //     resp.getWriter().println("Post failed " + name);
        // }
    }

   
}
